# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Psychorism
tagline:          'A Jekyll theme'
description:      'Psychologists + Algorithm<br> An Archive of Contributions made by Psychologists <a href="https://snu.ac.kr" target="_blank">@SNU</a>'
url:              https://github.com/Psychorism/
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
